### PR TITLE
Drop yarn classic in favour of pnpm

### PR DESCRIPTION
**Pull request by andreogle**
## Motivation

In an effort to reduce the collective time spent by API3 devs waiting for dependencies to install or scripts to run, as well as the amount of drive space required, I've switched from Yarn classic (which is now unmaintained) to [pnpm](https://pnpm.io/). Pnpm is mature and significantly faster than most other tools. Dependencies are hard-linked which saves on drive space.

I realise that there are now _many_ different projects under the API3 umbrella and this is exactly why I think we should consider migrating to pnpm. I don't particularly want 100 copies of Ethers.js on my machine.

Migrating is as simple as installing pnpm and replacing instances of `yarn` with `pnpm`. There are some _small_ differences here and there, but for the most part it's exactly the same API.

Let me know what you think

### CODE REVIEW

**Review by bbenligiray — APPROVED** [review]
I tried it out, works fine. I have two reservations
- I'd avoid it on repos that we expect others ([auditors](https://github.com/api3dao/nft-authorizer), [developers](https://github.com/api3dao/data-feed-reader-example), etc.) to use. I think it's unreasonable to ask people to install the package manager we prefer.
- I remember having a lot of trouble having symlinked dependencies make their way into the pack in Airnode pre-alpha. There's a good likelihood that switching the monorepo to pnpm will result in the next release to be botched unless a lot of care is put into making sure that it's fine (though this is not a reason not to switch).

**Comment by andreogle** [comment]
> I think it's unreasonable to ask people to install the package manager we prefer

Not sure I agree with this. It's a pretty common thing to do and pnpm is already roughly about as popular as yarn classic.

> trouble with symlinked dependencies

I think that was with Yarn 2? I know a lot of people have had issues with Yarn 2 in the past. For what it's worth, two of the most popular frontend frameworks use pnpm for managing their monorepos ([Vue](https://github.com/vuejs/core) and [Next.js](https://github.com/vercel/next.js))

That being said, if you're not comfortable switching and having some inconsistencies between how API3 projects manage dependencies, then I'm happy to close this PR. There are more important things to focus on than this. We can look at this later.

**Comment by bbenligiray** [comment]
> pnpm is already roughly about as popular as yarn classic

They may be equally popular in terms of active users but I'm referring to it being pre-installed on the user's machine. For example, even if the user normally uses npm, yarn commands work out of the box.

> I think that was with Yarn 2

That had to do with Serverless and how the deployment zip was packed. I mainly think that [this](https://github.com/api3dao/airnode/blob/master/packages/airnode-deployer/webpack.config.js) will need to be updated.

> That being said, if you're not comfortable switching and having some inconsistencies between how API3 projects manage dependencies, then I'm happy to close this PR. There are more important things to focus on than this. We can look at this later.

I think we should definitely not have our example projects etc. use pnpm. If you'd rather have us switch over altogether or not at all, then we shouldn't switch. Otherwise, it's a very small amount of extra work for a very small amount of benefit so I don't mind either way.

**Comment by andreogle** [comment]
> I think we should definitely not have our example projects etc. use pnpm. If you'd rather have us switch over altogether or not at all, then we shouldn't switch

Yeah this was my main concern - having a mix of yarn & pnpm. I still think we should migrate, but maybe now is not the time.

**Pull request closed without merging**
